### ISSUE TITLE
Add `projects` endpoint 

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#269]
Allow GET, POST and PUT.

A `project` should have the fields `id` and `phases`. Each phase should have `name`, `schedule`, `description` and 0...n `hearings`.

**Comment by Rikuoja** [comment]
Also, certain project phases may not be public for imported projects. Therefore, the endpoint should only return projects in public phase.

The project phase model, and public/non-public phases to create can be found in github.com/City-of-Helsinki/kaavapino .

**Comment by jussih** [comment]
**The actions user can take on a Project when filling out a Hearing form**

- Create new project with phases
  - The form will POST project and phase, new objects created in database

- Use existing project
  - Projects in `/v1/project` endpoint listed in dropdown
  - User selects one, phases in that project are populated into the hearing form and POSTed as is

- Use existing project, making modifications
  - Load project phases via dropdown
  - Add phase / remove phase / edit phase data
  - Changes will update the existing project, reflecting to other hearings associated to the project

**Open questions**
- What happens if user decides to remove a phase which has other hearings associated to it?
