### ISSUE TITLE
Allow setting project and project phase for Hearing in admin

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#321]
Currently, django-admin allows editing projects, but there is no way to specify the project or project phase in the Hearing admin. Just a simple drop-down to specify project, and another one to specify the phase in the project for the hearing, will do.

**Comment by jussih** [comment]
The hearing contains a foreign key to just the project phase, not the project since that is already implied by the project phase. Having a dropdown for the project is thus not practical.

I propose we expose the project phase as a raw id field in the Hearing admin, so we can get a popup selector for the phase in which we can filter by the project. See image.

![screenshot from 2018-07-30 17-13-11](https://user-images.githubusercontent.com/668554/43402794-3288e33a-941c-11e8-9549-b26e44b21723.png)
